# Ini adalah model platform pembiayaan yang didukung

github : KazeDevID
patreon  : #Ganti dengan satu nama pengguna Patreon
open_collective : # Ganti dengan satu nama pengguna Open Collective
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie : # Ganti dengan satu nama pengguna Otechie
lfx_crowdfunding   : # Ganti dengan satu nama proyek LFX Crowdfunding misalnya, cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
